image: docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

build and push latest:
  stage: build
  script:
    - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master-latest
    
build and push stable:
  stage: build
  script:
    - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull --tag $CI_REGISTRY_IMAGE:stable .
    - docker push $CI_REGISTRY_IMAGE:stable
  only:
    - master
