stages:
  - build-dev
  - build-release
  - artifacts
  - mkdocs
  - deploydocs

# 1. Development builds (Runs on branch push)
build dev base:
  stage: build-dev
  image: docker:latest
  tags:
    - dind-runner
  script:
    - echo "$CI_JOB_TOKEN" | docker login --username gitlab-ci-token --password-stdin $CI_REGISTRY
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" --password-stdin quay.io || echo "Quay.io login failed."
    # Build and tag as :dev
    - docker build --pull --build-arg VERSION=dev --tag $CI_REGISTRY_IMAGE:dev .
    - docker push $CI_REGISTRY_IMAGE:dev
    - docker tag $CI_REGISTRY_IMAGE:dev quay.io/ioer-fdz/carto-lab-docker:dev || true
    - docker push quay.io/ioer-fdz/carto-lab-docker:dev || echo "Quay push failed."
  rules:
    - if: $CI_COMMIT_BRANCH == "master-latest"
      changes:
        - Dockerfile
        - "*.yml"

# In .gitlab-ci.yml
build dev r:
  stage: build-dev
  image: docker:latest
  tags:
    - dind-runner
  script:
    - echo "$CI_JOB_TOKEN" | docker login --username gitlab-ci-token --password-stdin $CI_REGISTRY
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" --password-stdin quay.io || echo "Quay.io login failed."
    # Build and tag as :r_dev
    - docker build --pull --build-arg VERSION=dev --tag $CI_REGISTRY_IMAGE:r_dev ./r
    - docker push $CI_REGISTRY_IMAGE:r_dev
    - docker tag $CI_REGISTRY_IMAGE:r_dev quay.io/ioer-fdz/carto-lab-docker:r_dev || true
    - docker push quay.io/ioer-fdz/carto-lab-docker:r_dev || echo "Quay push failed."
  rules:
    - if: $CI_COMMIT_BRANCH == "master-latest"
      changes:
        - "r/**/*"
        - Dockerfile
        - "*.yml"

# 2. Release builds (Runs only on Git Tags)
build release base:
  stage: build-release
  image: docker:latest
  tags:
    - dind-runner
  script:
    - echo "$CI_JOB_TOKEN" | docker login --username gitlab-ci-token --password-stdin $CI_REGISTRY
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" --password-stdin quay.io || echo "Quay.io login failed."
    - docker build --pull --build-arg VERSION=$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE --all-tags
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG quay.io/ioer-fdz/carto-lab-docker:$CI_COMMIT_TAG || true
    - docker tag $CI_REGISTRY_IMAGE:latest quay.io/ioer-fdz/carto-lab-docker:latest || true
    - docker push quay.io/ioer-fdz/carto-lab-docker:$CI_COMMIT_TAG || echo "Quay push failed."
    - docker push quay.io/ioer-fdz/carto-lab-docker:latest || echo "Quay push failed."
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/

build release r:
  stage: build-release
  image: docker:latest
  tags:
    - dind-runner
  script:
    - echo "$CI_JOB_TOKEN" | docker login --username gitlab-ci-token --password-stdin $CI_REGISTRY
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" --password-stdin quay.io || echo "Quay.io login failed."
    - docker build --pull --build-arg VERSION=$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:r_$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:r_latest ./r
    - docker push $CI_REGISTRY_IMAGE --all-tags
    - docker tag $CI_REGISTRY_IMAGE:r_$CI_COMMIT_TAG quay.io/ioer-fdz/carto-lab-docker:r_$CI_COMMIT_TAG || true
    - docker tag $CI_REGISTRY_IMAGE:r_latest quay.io/ioer-fdz/carto-lab-docker:r_latest || true
    - docker push quay.io/ioer-fdz/carto-lab-docker:r_$CI_COMMIT_TAG || echo "Quay push failed."
    - docker push quay.io/ioer-fdz/carto-lab-docker:r_latest || echo "Quay push failed."
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/

# 3. Docs & Artifacts
artifacts:
  image: "gcr.hrz.tu-chemnitz.de/ioer/fdz/container-images/miniconda-cidefault:0.9.1"
  before_script:
    # Inject Conda shell functions directly into the non-interactive CI shell
    - source /opt/conda/etc/profile.d/conda.sh
    # Activate default ci_env from registry image
    # contains anybadge
    - conda activate ci_env
  stage: artifacts
  script:
    - cp CHANGELOG.md docs/changelog.md
    - version_var=$(sed -n "s#__version__ =\s*'\(.*\)'#\1#p" .version)
    - anybadge -l version --value="${version_var}" --file=version.svg --color=#0970B9
    - anybadge -l mkdocs --value="Documentation" --file=documentation.svg --color=green
  artifacts:
    paths:
      - '*.svg'
      - docs/changelog.md
  rules:
    - if: $CI_COMMIT_BRANCH == "master-latest"

mkdocs:
  stage: mkdocs
  image: registry.gitlab.vgiscience.org/tools/mkdocs:0.4.0
  script:
    - mkdocs build
    - cp *.svg "site/"
  artifacts:
    name: site
    paths:
    - site
  rules:
    - if: $CI_COMMIT_BRANCH == "master-latest"

deploydocs:
  stage: deploydocs
  image: "registry.gitlab.vgiscience.org/tud_ifk/rsync-ssh-alpine:alpine3.17-r0-v4"
  before_script:
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVKEY}" | ssh-add -
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\tLogLevel QUIET\n\n" > ~/.ssh/config'
  script:
  - rsync -avu -zz --no-perms --omit-dir-times --chown=www-data:www-data --chmod=D775,F664 site/ "${PRODUCTION_DESTINATION}"/public/cartolab/
  only:
    - master-latest