services:
  jupyterlab:
    image: quay.io/ioer-fdz/carto-lab-docker:${TAG:-latest}
    build:
      context: .
      args:
        ENVIRONMENT_FILE: ${ENVIRONMENT_FILE:-environment_default.yml}
        WORKER_ENV_NAME: ${WORKER_ENV_NAME:-worker_env}
        VERSION: ${TAG}
