services:
  jupyterlab:
    image: quay.io/ioer-fdz/carto-lab-docker:${TAG:-mapnik}
    build:
      context: ./mapnik
      args:
        VERSION: ${TAG:-latest}
    volumes:
      # Appended to the base volumes from docker-compose.yml
      - ${MAPNIK_FONTS:-/usr/share/fonts}:/fonts
