services:
  jupyterlab:
    image: gcr.hrz.tu-chemnitz.de/ioer/fdz/carto-lab-docker:grass
    build:
      context: ./grass
      args:
        - VERSION=${TAG:-latest}
    container_name: ${CONTAINER_NAME:-lbsn-jupyterlab}
    restart: "no"
    ports:
      - 127.0.0.1:${JUPYTER_WEBPORT:-8888}:8888
    volumes:
      - ${JUPYTER_NOTEBOOKS:-~/notebooks}:/home/jovyan/work
      - ${CONDA_ENVS:-~/envs}:/envs
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-eX4mP13p455w0Rd}
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD:-eX4mP13p455w0Rd}
      - JUPYTER_WEBURL=${JUPYTER_WEBURL:-http://localhost:8888}
      - JUPYTER_EXTRA_ARGS=${JUPYTER_EXTRA_ARGS:-}
    env_file: ".env"
    networks:
      - lbsn-network

networks:
  lbsn-network:
    name: ${NETWORK_NAME:-lbsn-network}
    external: true
