version: '3.6'

services:

  jupyterlab:
    build: .
    image: lbsn/jupyterlab
    container_name: jupyterlab
    restart: always
    ports:
      - 127.0.0.1:${JUPYTER_WEBPORT:-8888}:8888
    volumes:
      - ${JUPYTER_HOME:-/data/lbsn/jupyter}:/home/jovyan/work
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - lbsn-network

networks:
  lbsn-network:
    name: ${NETWORK_NAME:-lbsn-network}
    external: true
