name: worker_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - adjusttext
  - bokeh
  - contextily
  - colorcet
  - esda
  - geoviews-core
  - holoviews
  - ipywidgets
  - ipyleaflet
  - datashader
  - dask>=0.17.1,<2025.1.0
  - descartes
  - geoalchemy2
  - geopandas
  - geopy
  - hvplot
  - flopy
  - ipython-sql
  - numpy
  - mapclassify
  - matplotlib-venn
  - matplotlib-scalebar
  - memory_profiler
  - mmh3
  - pyarrow
  - pyepsg
  - psycopg2
  - python-dotenv
  - rasterio
  - seaborn
  - shapely
  - tagmaps
  - xarray
  - pip:
    - python-hll2
