name: worker_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - colorcet
  - 'geoviews-core=1.8.1'
  - 'ipywidgets=7.5.*'
  - descartes
  - geoalchemy2
  - geopandas
  - ipython-sql
  - mapclassify
  - matplotlib-venn
  - memory_profiler
  - psycopg2
  - python-dotenv
  - seaborn
  - xarray
  - selenium
  - geckodriver
  - python-chromedriver-binary