name: jupyter_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jupyterlab>=3
  # - jupyterlab-git
  - jupytext
  - jupyterlab_widgets
  - nbconvert=6.5.0 # nbconvert often has issues with latest release candidates, pin to stable
  - nbclassic # for backwards compatibility
  - papermill
  - pyviz_comms
  - pip:
    - jupyterlab-spellchecker