name: jupyter_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - notebook<7.0.0 # pin until https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/issues/165 is solved
  - jupyterlab>=4
  - jupyter-collaboration
  - jupyterlab-git
  # - jupyterlab-git
  - jupytext
  - jupyterlab_widgets
  - nbconvert
  - nbclassic # for backwards compatibility
  - papermill
  - pyviz_comms
  - pip:
    - jupyterlab-spellchecker
    - jupyter_contrib_nbextensions # https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1650