name: jupyter_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - jupyterlab>=4
  # - jupyterlab-git
  - jupytext
  - jupyterlab_widgets
  - nbconvert
  - nbclassic # for backwards compatibility
  - papermill
  - pyviz_comms
  - pip:
    - jupyterlab-spellchecker
    - notebook==6.5.5 # needed for passwd in Dockerfile