site_name: Carto-Lab Docker Documentation
site_url: https://cartolab.fdz.ioer.info/
site_author: Alexander Dunkel
copyright: CC BY 4.0, Alexander Dunkel, Marc Löchner, IOER FDZ & vgiscience.org colleagues, and contributors

repo_url: https://github.com/ioer-dresden/carto-lab-docker
edit_uri: edit/master-latest/docs/
site_dir: site
docs_dir: docs

theme:
  name: 'readthedocs'
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - bash
  collapse_navigation: true
  custom_dir: docs/overrides
  logo: images/logo-white-text.svg

extra_css:
  - css/extra.css
  - css/all.min.css

extra_javascript:
  - js/popper.min.js
  - js/tippy-bundle.umd.js
  - js/clipboard.min.js
  - js/extra.js

markdown_extensions:
    - toc:
        permalink: true
    - markdown_include.include:
        base_path: docs
    - admonition
    - fenced_code
    - sane_lists

plugins:
    - search
    - mermaid2

nav:
    - Introduction: index.md
    - Quick-Start: quickstart.md
    - User Guide:
        - Docker Container Setup: docker.md
        - JupyterLab: jupyter.md
        - Python: python.md
        - R: r.md
        - Mapnik: mapnik.md
        - Grass: grass.md
        - User Workflows: use-cases.md
        - Live Collaboration: collaboration.md
        - Example Notebooks: notebooks.md
        - Additional resources: resources.md
    - Developers:
        - Configuration: configuration.md
        - Developer Workflows: developers.md
        - Compatibility Matrix: matrix.md
        - Changelog: changelog.md
    - About: about.md
