site_name: Carto-Lab Docker Documentation
site_url: https://cartolab.theplink.org/
site_author: Alexander Dunkel
copyright: CC BY 4.0, Alexander Dunkel, Marc Löchner, vgiscience.org and contributors

repo_url: https://gitlab.vgiscience.de/lbsn/tools/jupyterlab
site_dir: site
docs_dir: docs

theme:
  name: 'readthedocs'
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - bash
  collapse_navigation: true
  custom_dir: docs/overrides

extra_css:
  - extra.css

markdown_extensions:
    - toc:
        permalink: true
    - markdown_include.include:
        base_path: docs
    - admonition
    - fenced_code
    - sane_lists

plugins:
    - search

nav:
    - Introduction: index.md
    - Quick-Start: quickstart.md
    - User Guide:
        - Docker Container Setup: docker.md
        - JupyterLab: jupyter.md
        - Python: python.md
        - R: r.md
        - Mapnik: mapnik.md
        - Grass: grass.md
        - Tasks: use-cases.md
        - Live Collaboration: collaboration.md
        - Example Notebooks: notebooks.md
        - Additional resources: resources.md
    - Developers:
        - Configuration: configuration.md
        - Tasks: developers.md
        - Changelog: changelog.md
    - About: about.md
